### ISSUE TITLE
Off-by-one error in `Util.Position.getSpan`?

### ISSUE THREAD

**Issue by buggymcbugfix** [camfort/fortran-src#46] opened 2017-06-08 10:31 UTC
`Util.Position.getSpan` seems to have an off-by-one error, which gets revealed in the source spans that are spat out by `units-check` as part of the constraints.

They are all short by one, e.g. `(12:9)-(12:19)` should really be `(12:9)-(12:20)`.

This is assuming that we start both lines and columns at 1 (from my observation Vim and Atom do this, but Emacs starts lines at 1 and columns at 0).

**Comment by dorchard** [comment] 2017-06-08 11:08
This can observed apart from `units-check`, e.g. take the file
```
program tiny
  implicit none
  real :: x
end program tiny
```
and putting this through `fortran-src`, we get the following AST (fragment):
```
........
     (3:11)-(3:11)
                                                       [DeclVariable ()
                                                                     (3:11)-(3:11)
                                                                     (ExpValue ()
                                                                               (3:11)-(3:11)
                                                                               (ValVariable "x"))
                                                                     Nothing
                                                                     Nothing]))]
```
Note that the span for `x` has zero length.

**Comment by vimuel** [comment] 2017-06-18 10:32
@madgen Can you give me a pointer to where I should start looking to fix this?

**Comment by madgen** [comment] 2017-06-18 14:30
@vimuel `Lexer/FreeForm.x` in particular `alexGetByte`. If you have any questions as to how it work just let me know.

**Comment by harry-clarke** [comment] 2017-07-06 12:33
@dorchard, from that example code, are all the end spans one off?
Looking at the file 1-indexed, the 11th character of line 3 is where the variable "x" starts.

There is no 12th character, but you could say that variable "x" should have span (3:11)-(3:12) if all end spans should point to the character after the end of the statement.

**Comment by dorchard** [comment] 2017-07-06 14:23
That is a good question- I guess we have to pick a convention and stick to it- I think a lot of the camfort side code assumes that the upper bound is exclusive, i.e. a single letter variable like `x` will have a span (l:c)-(l:c+1).
Is this convention used in fortran-src @madgen and @mrd ?

**Comment by GuiltyDolphin** [comment] 2017-07-07 09:24
@dorchard I agree... And we should ensure we can't violate this convention (i.e., deal with it in fortran-src and prevent access to span internals).

**Comment by burz** [comment] 2018-11-12 22:53
This is a ***big*** problem for `SrcSpan`s related to `BlIf` (i.e. if blocks).

As a trivial example, consider the following:

```fortran
      subroutine foo
      if (.TRUE.) then
      print *, 'I print'
      endif
      end
```

The `SrcSpan` for this block shows that its end is the the last character (`'`) in the `print` line.

Ok, so maybe this isn't so bad, we can *probably* assume that the real end to the `BlIf` is one additional line down and `6 + 5` characters over (6 for indentation).

On the other hand the problem is *much much* worse for if the if blocks are *nested*.

```fortran
      subroutine bar
      if (.TRUE.) then
      if (.TRUE.) then
      if (.TRUE.) then
      if (.TRUE.) then
      print *, 'I print'
      endif
      endif
      endif
      endif
      end
```

For ***every*** `BlIf` in the above code, the corresponding `SrcSpan`'s end is the last character (`'`) in the `print` line.

This means that in order to even think about determining the span of any if statement anywhere using `fortran-src` we need to traverse the tree all the way down and pull up the (possibly different) end of the span on the way up. *And this may not even be able to be done correctly if the `endif`s are not all the way to the left (i.e. 6 characters from the left).*

I have a very hard time thinking of any reasons why the current system would be useful given the nesting problem.

Would a fix for this issue be accepted?

**Comment by madgen** [comment] 2018-11-13 00:02
@burz Good catch though I think this is a separate bug than the original one. I must have messed something up while grouping statements into blocks. [Grouping.hs](https://github.com/camfort/fortran-src/blob/master/src/Language/Fortran/Transformation/Grouping.hs) should be the place to look for this. The chances are I'm discarding the `END...` statements somewhere. So when I try to calculate the `SrcSpan` of the whole block it looks at the last "real" statement.

It would be a great if you can look into this. It has been a while but I can't think of any way, the way it is is correct. It would be good to open a separate issue for this.

**Closed** 2019-05-07 13:51 UTC
Labels: Type: Bug
